### ISSUE TITLE
A better introduction

### ISSUE THREAD

**Issue by PythonLinks** [midhunvnadh/Open-Proxy-Project#3]
For the less technical, a brief explanation of what a proxy is and why it is important.  Here is a draft text. 

A proxy server lets you access the internet through that proxy.  So if certain content is banned in your country, if you access it through a proxy, the server will think that you in that other country, and you will be able to view the content. 

Sometimes content is banned for bad reasons sometimes for good reasons.  It could be that the content is being censored in your country, it could be that the web site does not follow the law in your country, for example it is not GDPR compliant.  In either case a proxy can enable you to see the content. 

Of course proxies consume band width, and so we never have enough of them.  If you want to help fight censorship, please offer to host a proxy.  You can find the software and installation instructions here.

**Comment by midhunvnadh** [comment]
Thanks for this content!

**Comment by midhunvnadh** [comment]
The content has been added!

**Comment by PythonLinks** [comment]
Thank you.  I wrote it late at night, if you actually read it, it needs a few edits.  I edited it this morning.  Maybe you can copy the new version over.  

The last line, it needs links to where the software and instructions for running a proxy are located.

**Comment by midhunvnadh** [comment]
Could you please do a pull request?
